<?php

namespace MailPoetVendor;

if (!defined('ABSPATH')) exit;


// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInit3fe5fd009e11b8b0420131e5a0cc7d08::getLoader();
